{agent: {motion_automaton: MoatTestDroneBad, on_device: cyphyhousecopter, pid: 0, plist: []},
  device: {bot_name: cyphyhousecopter, bot_type: QUAD, ip: '', motion_automata: [MoatTestDroneBad],
    planner: RRT_DRONE, port: 2000, positioning_topic: {topic: /vrpn_client_node/, type: PoseStamped},
    queue_size: 10, reached_topic: {topic: reached, type: String}, ros_node_prefix: waypoint_node,
    waypoint_topic: {topic: waypoint, type: PoseStamped}}, leader_pid: 0, mutex_handler: BaseMutexHandler,
  num_agents: 1}
