agent:
  motion_automaton: str()
  on_device: str()
  pid: int()
  plist: list()
device:
  bot_name: str()
  bot_type: str()
  ip: ip()
  motion_automata: list()
  planner: str()
  r_port: int()
  positioning_topic:
    topic: str()
    type: str()
  queue_size: int()
  reached_topic:
    topic: str()
    type: str()
  ros_node_prefix: str()
  waypoint_topic:
    topic: str()
    type: str()
leader_pid: int()
mutex_handler: str()
num_agents: int()