#!/usr/bin/python
import argparse


def get_opt_args():
    parser = argparse.ArgumentParser()
    group = parser.add_argument_group()
    group.add_argument('-a', '--app', action='store')
    group.add_argument('-c', '--config', action='store')
    args = parser.parse_args()
    appfile = args.app
    configfile = args.config
    return (appfile, configfile)


def get_app_name(appfile):
    appcode = open(appfile).read()
    end = appcode.find("(AgentThread)")
    begin = appcode[:end].rfind("class ") + 6
    appname = appcode[begin:end].strip()
    return appname


def import_app(appfile, appname):
    import importlib.util
    spec = importlib.util.spec_from_file_location(appname, appfile)
    foo = importlib.util.module_from_spec(spec)
    return spec, foo


def run_app(app_name):
    pass


if __name__ == '__main__':
    appfile = get_opt_args()[0]
